spring.datasource.url=jdbc:mysql://localhost:3306/team4_db
spring.datasource.username=root <-- Replace with your actual MySQL username
spring.datasource.password=8459 <-- Replace with your actual MySQL password
spring.jpa.hibernate.ddl-auto=update